name: Deploy via Pelican on GitHub pages

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  pelican:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2.3.4

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2.1.3
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v2.1.3
      with:
        path: |
          ~/.cache/peru
        key: ${{ runner.os }}-peru-${{ hashFiles('**/peru.yaml/*') }}
        restore-keys: |
          ${{ runner.os }}-peru-

    - uses: iranzo/gh-pages-pelican-action@1.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        SOURCE_FOLDER: content
        PELICAN_CONFIG_FILE: publishconf.py
